name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: PlatIAgro - Checkout 🛎️
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false

    - name: Download claat and Add to Path
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        wget -O $GITHUB_WORKSPACE/bin/claat https://github.com/googlecodelabs/tools/releases/download/v2.2.0/claat-linux-amd64
        echo "::add-path::$GITHUB_WORKSPACE/bin"
        chmod +x $GITHUB_WORKSPACE/bin/claat

    - name: PlatIAgro Introduction - Build 🔧 # This example project is built using claat and outputs the result to the 'platiagro-introduction' folder.
      run: |
        claat export codelabs/platiagro-introduction/codelab.md

    - name: Machine Failure - Build 🔧 # This example project is built using yarn and outputs the result to the 'build' folder.
      run: |
        cd machine-failure
        yarn
        yarn build
      env:
        PUBLIC_URL: https://platiagro.github.io/tutorials/machine-failure/

    - name: Machine Failure Dojot - Build 🔧 # This example project is built using yarn and outputs the result to the 'build' folder.
      run: |
        cd machine-failure-dojot
        yarn
        yarn build
      env:
        PUBLIC_URL: https://platiagro.github.io/tutorials/machine-failure-dojot/

    - name: PlatIAgro Tasks - Build 🔧 # This example project is built using claat and outputs the result to the 'platiagro-tasks' folder.
      run: |
        claat export codelabs/platiagro-tasks/codelab.md
        claat export codelabs/platiagro-tasks/linear-regression.md

    - name: PlatIAgro Tutorial Projeto - Build 🔧 # This example project is built using claat and outputs the result to the 'platiagro-tasks' folder.
      run: |
        claat export codelabs/Tutorial-projeto-experimento/Projeto.md

    - name: PlatIAgro Tutorial Experimento - Build 🔧 # This example project is built using claat and outputs the result to the 'platiagro-tasks' folder.
      run: |
        claat export codelabs/Tutorial-projeto-experimento/Experimento.md

    - name: PlatIAgro Tutorial Aprendizado de Maquina - Build 🔧 # This example project is built using claat and outputs the result to the 'platiagro-aprendizado-maquina' folder.
      run: |
        claat export codelabs/aprendizado-maquina/codelab.md

    - name: PlatIAgro Tutorial Aprendizado de Maquina - Build 🔧 # This example project is built using claat and outputs the result to the 'platiagro-aprendizado-maquina' folder.
      run: |
        claat export codelabs/platiagro-dojot/codelab.md

    - name: Codelabs Site - Build 🔧 # This example project is built using gulp and outputs the result to the 'dist' folder.
      run: |
        yarn
        ./node_modules/.bin/gulp dist --base-url https://platiagro.github.io/tutorials
        rm dist/codelabs
        mkdir -p dist/codelabs
        mv platiagro-introduction dist/codelabs/
        mv machine-failure/build dist/machine-failure
        mv platiagro-dojot dist/codelabs/
        mv machine-failure-dojot/build dist/machine-failure-dojot
        mv platiagro-tasks dist/codelabs/
        mv projeto-tutorial-platiago dist/codelabs/
        mv tutorial-experimento-platiagro dist/codelabs/
        mv aprendizado-maquina dist/codelabs/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
